services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - apt_network

  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${REDIS_CONTAINER}
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - apt_network

  migration:
    image: ghcr.io/kukymbr/goose-docker:latest
    container_name: apt_migration
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=$DB_SSLMODE
      - GOOSE_COMMAND=up
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - apt_network

  backend:
    image: ${BACK_END_IMAGE}:latest
    container_name: apt_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - apt_network

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: ${PGADMIN_CONTAINER}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - apt_network

volumes:
  pg_data:
  redis_data:

networks:
  apt_network:
    driver: bridge
